### ISSUE TITLE
RuntimeError: shape '[-1, 3, 224, 224]' is invalid for input of size 12288

### ISSUE THREAD

**Issue by Chunssu** [zhang-can/PAN-PyTorch#16]
在测试somethingv2数据集的时候出现如下问题，在En.sh,Full.sh,Lite.sh三个测试脚本上都会有如下情况。
I found RuntimeError when I running somethingv2 test scripts. 

Traceback (most recent call last):
  File "C:\Users\ganjunsi\Downloads\PAN\test_models.py", line 289, in <module>
    rst = eval_video((i, data, label), net, n_seg, modality)
  File "C:\Users\ganjunsi\Downloads\PAN\test_models.py", line 128, in eval_video
    rst = net(data_in)
  File "C:\Users\ganjunsi\.conda\envs\gjs-pan\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ganjunsi\.conda\envs\gjs-pan\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\ganjunsi\.conda\envs\gjs-pan\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ganjunsi\Downloads\PAN\ops\models.py", line 290, in forward
    PA = self.PA(input)
  File "C:\Users\ganjunsi\.conda\envs\gjs-pan\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\ganjunsi\Downloads\PAN\ops\PAN_modules.py", line 28, in forward
    PA = d.view(-1, 1*(self.n_length-1), h, w)
RuntimeError: shape '[-1, 3, 224, 224]' is invalid for input of size 12288

**Comment by ZikkyZhou** [comment]
我也遇到了这个问题，请问您解决了吗？

**Comment by XanderDD** [comment]
python3.6会出现，改成3.8就好了

**Comment by Chunssu** [comment]
> python3.6会出现，改成3.8就好了

我用的是python3.9，有这个问题。

**Comment by kylin-12** [comment]
> > python3.6会出现，改成3.8就好了
> 
> 我用的是python3.9，有这个问题。

想问下这个问题解决了嘛，我用的python3.8，但还是有类似的问题，不过我的帧不是224x224的

**Comment by kevio33** [comment]
请问解决了吗，我训练的时候也出现了，我用的kinetics数据集，裁剪的224×224

**Comment by BeyondGod667** [comment]
解决了吗？
